<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DzUser\Module'                           => __DIR__ . '/Module.php',
  'spec\DzUser\Entity\UserSpec'             => __DIR__ . '/spec/DzUser/Entity/UserSpec.php',
  'DzUser\Controller\UserController'        => __DIR__ . '/src/DzUser/Controller/UserController.php',
  'DzUser\Entity\Role'                      => __DIR__ . '/src/DzUser/Entity/Role.php',
  'DzUser\Entity\RoleTrait'                 => __DIR__ . '/src/DzUser/Entity/RoleTrait.php',
  'DzUser\Entity\User'                      => __DIR__ . '/src/DzUser/Entity/User.php',
  'DzUser\Entity\UserTrait'                 => __DIR__ . '/src/DzUser/Entity/UserTrait.php',
  'DzUser\Mapper\User'                      => __DIR__ . '/src/DzUser/Mapper/User.php',
  'DzUser\Mapper\UserInterface'             => __DIR__ . '/src/DzUser/Mapper/UserInterface.php',
  'DzUser\Test\Helper\Db'                   => __DIR__ . '/src/DzUser/Test/Helper/Db.php',
  'DzUser\Test\Helper\WebHelperDbTrait'     => __DIR__ . '/src/DzUser/Test/Helper/WebHelperDbTrait.php',
  'DzUser\View\Helper\DzUserIdentityWidget' => __DIR__ . '/src/DzUser/View/Helper/DzUserIdentityWidget.php',
  'Codeception\Module\CodeHelper'           => __DIR__ . '/tests/_helpers/CodeHelper.php',
  'Codeception\Module\TestHelper'           => __DIR__ . '/tests/_helpers/TestHelper.php',
  'Codeception\Module\WebHelper'            => __DIR__ . '/tests/_helpers/WebHelper.php',
  'WebGuy'                                  => __DIR__ . '/tests/acceptance/WebGuy.php',
  'TestGuy'                                 => __DIR__ . '/tests/functional/TestGuy.php',
  'CodeGuy'                                 => __DIR__ . '/tests/unit/CodeGuy.php',
);
