<?php

/**
 * Vue pour l'action UserController::indexAction()
 * Affiche les informations du module
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzUser
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzUser/blob/master/view/dz-user/user/index.phtml
 */

?>

<?php $this->headTitle('Informations'); ?>

<h1>DzUser</h1>

<p>DzUser est un module de gestion d'utilisateurs pour ZF2, compatible Doctrine. C'est une surcouche de <a href="https://github.com/ZF-Commons/ZfcUser">ZfcUser</a>. Il est écrit et maintenu par Adrien Desfourneaux (aka Dieze) &lt;dieze51@gmail.com&gt;. Le projet est hébergé par GitHub à l'adresse <a href="https://github.com/dieze/DzUser.git">https://github.com/dieze/DzUser.git</a></p>

<h2>Fonctionnalités</h2>

<span style="color:red">TODO</span>

<p>L'aide de vue <em>DzUserIdentityWidget</em> est un widget qui affiche un formulaire de connexion si l'utilisateur n'est pas authentifié. Dans le cas contraire, affiche le profil de l'utilisateur connecté. Par défaut, on n'affiche pas le titre dans le widget, mais on peut forcer l'affichage du titre avec l'option <em>hasTitle</em> à true. L'option <em>hasRegistration</em> permet d'afficher ou non le lien d'inscription ; noter que le lien d'inscription ne s'affichera jamais si l'option de zfcuser enable_registration est à false. Les options <em>redirectLoginSuccess</em> et <em>redirectLoginFailure</em> permettent une redirection repectivement quand la connexion réussie ou quand la connexion échoue. L'option <em>redirectLogout</em> permet une redirection à la déconnexion de l'utilisateur.</p>

<style>
    .widget-examples {
        list-style-type: none;
    }

    .widget-examples > li {
        display: inline-block;
        vertical-align: top;
        border: 1px solid black;
        border-radius: 0 0 5px 5px;
        margin: 10px;
    }

    .widget-container {
        padding: 10px;
    }
</style>

<ul class="widget-examples">
    <li>
        <pre>&lt;?php
$this->dzUserIdentityWidget();
?&gt;</pre>
        <div class="widget-container">
            <?php echo $this->dzUserIdentityWidget(); ?>
        </div>
    </li>

    <li>
        <pre>&lt;?php
echo $this->dzUserIdentityWidget(
    array(
        'hasTitle' => true
    )
);?&gt;</pre>
        <div class="widget-container">
            <?php
            echo $this->dzUserIdentityWidget(
                array(
                    'hasTitle' => true
                )
            );
            ?>
        </div>
    </li>

    <li>
        <pre>&lt;?php
echo $this->dzUserIdentityWidget(
    array(
        'hasRegistration' => false
    )
);?&gt;</pre>
        <div class="widget-container">
            <?php
            echo $this->dzUserIdentityWidget(
                array(
                    'hasRegistration' => false
                )
            );
            ?>
        </div>
    </li>

    <li>
        <pre>
&lt;?php
echo $this->dzUserIdentityWidget(
    array(
        'redirectLoginSuccess' => $this->url(),
        'redirectLoginFailure' => $this->url(),
        'redirectLogout' => $this->url()
    )
);
?&gt;</pre>
        <div class="widget-container">
            <?php 
            echo $this->dzUserIdentityWidget(
                array(
                    'redirectLoginSuccess' => $this->url(),
                    'redirectLoginFailure' => $this->url(),
                    'redirectLogout' => $this->url()
                )
            );
            ?>
        </div>
    </li>

</ul>
