<?php

/**
 * Vue pour l'action UserController::indexAction()
 * Informations du module
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzUser
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzUser/blob/master/view/dz-user/user/index.phtml
 */

?>

<h1>DzUser : Module ZF2 de gestion d'utilisateur</h1>

<h2>Informations</h2>

<dl>
  <dt>Auteur</dt>
  <dd>Adrien Desfourneaux (aka Dieze51) &lt;dieze51@gmail.com&gt;</dd>
  
  <dt>Dépôt</dt>
  <dd>https://github.com/dieze/DzUser.git</dd>
</dl>

<h2>Widgets</h2>

<h3>dzUserIdentityWidget</h3>

<p>
	Widget qui affiche un formulaire de connexion si l'utilisateur n'est pas authentifié. Dans le cas contraire, affiche le profil de l'utilisateur connecté.
</p>

<p>
	&lt;php echo $this->dzUserIdentityWidget(); ?&gt;
</p>

<?php echo $this->dzUserIdentityWidget(); ?>