<?php

/**
 * Vue pour le Widget DzUserIdentityWidget pour le visiteur
 * Affiche le formulaire de connexion au visiteur
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzUser
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzUser/blob/master/view/dz-user/user/loginWidget.phtml
 */

?>

<div class="login-widget">
    <?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    ?>

    <?php echo $this->form()->openTag($form) ?>

        <dl class="zend_form">
            <?php echo $this->formElementErrors($form->get('identity')) ?>

            <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
            <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

            <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
            <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

            <?php
            if ($this->redirect) :
                ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php
            endif
            ?>

            <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
        </dl>

    <?php echo $this->form()->closeTag() ?>

    <?php
    if ($this->enableRegistration) :
        ?>
        Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
        <?php
    endif;
    ?>
</div>
