<?php

/**
 * Vue pour l'action UserController::loginAction()
 * Affiche le formulaire de connexion au visiteur
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzUser
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzUser/blob/master/view/dz-user/user/login.phtml
 */

?>

<?php
if (isset($this->isWidget) && $this->isWidget) {
    ?>
<div class="login-widget">
    <?php
}
?>

<?php
if ($this->hasTitle) {
    ?>
<h1>Connexion</h1>
    <?php
}
?>

<?php
$form = $this->loginForm;
$form->prepare();

$strErrors = $this->formElementErrors($form->get('identity'));
if($strErrors != '') {
    $class = $form->getAttribute('class');
    if ($class !== null) {
        $class = $class . ' has-error';
    } else {
        $class = 'has-error';
    }
    $form->setAttribute('class', $class);
}

$form->setAttribute('action', $this->url('dzuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php
        echo $this->formElementErrors($form->get('identity'),
            array(
                'class' => 'help-block',
            )
        );
        ?>

        <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
        <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
        <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

        <?php if ($this->redirectSuccess): ?>
            <input type="hidden" name="redirectSuccess" value="<?php echo $this->escapeHtml($this->redirectSuccess) ?>" />
        <?php endif ?>

        <?php if ($this->redirectFailure): ?>
            <input type="hidden" name="redirectFailure" value="<?php echo $this->escapeHtml($this->redirectFailure) ?>" />
        <?php endif ?>

        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
<a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Inscription</a>
<?php endif; ?>

<?php
if (isset($this->isWidget) && $this->isWidget) {
    ?>
</div>
    <?php
}
?>
