<?php

/**
 * Vue pour le Widget DzUserIdentityWidget pour l'utilisateur connecté
 * Affiche le profil de l'utilisateur connecté
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzUser
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzUser/blob/master/view/dz-user/user/profileWidget.phtml
 */

?>

<div class="profile-widget">
	<div class="gravatar">
		<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
	</div>

	<h3 class="logged-msg"><?php echo $this->zfcUserDisplayName() ?></h3>

	<a class="action" href="<?php echo $this->url('zfcuser/logout') ?>">Déconnexion</a>
</div>
