/*
Passwords bcrypt
Generated by http://bcrypthashgenerator.apphb.com/
johndoe		$2a$10$cGjT9d1c95HXTNusF9Vxaupaa89wfGUPirtTUii0ZEvvzAYNEBYhC
janedoe		$2a$10$kcIWTiSvKHXIwBR8vqamOeChTYDL6XarKm9pcBWW9ropyepEiFXJu
*/

INSERT INTO user_role (role_id, is_default, parent) VALUES ('user', 1, '');
INSERT INTO user_role (role_id, is_default, parent) VALUES ('admin', 0, 'user');
INSERT INTO user_role (role_id, is_default, parent) VALUES ('projectmanager', 0, 'user');

INSERT INTO user (user_id, username, email, display_name, password, state) VALUES (1, 'johndoe', 'john@doe.com', 'John Doe', '$2a$10$cGjT9d1c95HXTNusF9Vxaupaa89wfGUPirtTUii0ZEvvzAYNEBYhC', 1);
INSERT INTO user (user_id, username, email, display_name, password, state) VALUES (2, 'janedoe', 'jane@doe.com', 'Jane Doe', '$2a$10$kcIWTiSvKHXIwBR8vqamOeChTYDL6XarKm9pcBWW9ropyepEiFXJu', 1);

INSERT INTO user_role_linker (user_id, role_id) VALUES (1, 'projectmanager');
INSERT INTO user_role_linker (user_id, role_id) VALUES (2, 'admin');