/*
Passwords bcrypt
Generated by http://bcrypthashgenerator.apphb.com/
johndoe    $2a$10$cGjT9d1c95HXTNusF9Vxaupaa89wfGUPirtTUii0ZEvvzAYNEBYhC
janedoe    $2a$10$kcIWTiSvKHXIwBR8vqamOeChTYDL6XarKm9pcBWW9ropyepEiFXJu
jeanmichel $2a$10$r/t40Kr5quLc0SGhvCru0eIQKi/SlgysxzIKj.xkK1Ya.rm721Nnm
*/

INSERT INTO user_role (role_id, is_default, parent) VALUES ('user', 1, '');
INSERT INTO user_role (role_id, is_default, parent) VALUES ('admin', 0, 'user');
INSERT INTO user_role (role_id, is_default, parent) VALUES ('projectmanager', 0, 'user');

INSERT INTO user (
    user_id,
    username,
    email,
    display_name,
    password,
    state
) VALUES (
    1,
    'johndoe',
    'john@doe.com',
    'John Doe (Chef de projet)',
    '$2a$10$cGjT9d1c95HXTNusF9Vxaupaa89wfGUPirtTUii0ZEvvzAYNEBYhC',
    1
);

INSERT INTO user_role_linker (user_id, role_id) VALUES (1, 'projectmanager');

INSERT INTO user (user_id,
    username,
    email,
    display_name,
    password,
    state
) VALUES (
    2,
    'janedoe',
    'jane@doe.com',
    'Jane Doe (Admin)',
    '$2a$10$kcIWTiSvKHXIwBR8vqamOeChTYDL6XarKm9pcBWW9ropyepEiFXJu',
    1
);

INSERT INTO user_role_linker (user_id, role_id) VALUES (2, 'admin');

INSERT INTO user (
    user_id,
    username,
    email,
    display_name,
    password,
    state
) VALUES (
    3,
    'jeanmichel',
    'jean@michel.com',
    'Jean Michel (Chef de projet)',
    '$2a$10$r/t40Kr5quLc0SGhvCru0eIQKi/SlgysxzIKj.xkK1Ya.rm721Nnm',
    1
);

INSERT INTO user_role_linker (user_id, role_id) VALUES (3, 'projectmanager');